=begin
#Clever API

#The Clever API

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0-SNAPSHOT

=end

require 'uri'

module Clever
  module UrlHelper
    def self.escape(url)
      URI::DEFAULT_PARSER.escape(url)
    end
  end
end
